services:
  web:
    build: .
    restart: always
    container_name: 'django_app'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/MiniMarket
    ports:
      - '8000:8000'
