# Generated by Django 5.0 on 2023-12-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_tax', to='MarketApp.tax'),
        ),
    ]
